[package]
name = "orna-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
futures-util = "0.3.31"
orna-artifact = { path = "../orna-artifact" }
orna-core = { path = "../orna-core" }
orna-protocol = { path = "../orna-protocol" }
orna-protocol-v1 = { path = "../orna-protocol-v1" }
orna-runtime-tty = { path = "../orna-runtime-tty" }
sha2 = "0.11.0"
orna-standard = { path = "../orna-standard" }
libloading = "0.9.0"
serde_json = "1.0.151"
stacker = "0.1.25"
reqwest = { version = "0.12.7", default-features = false, features = ["json", "rustls-tls-webpki-roots", "http2", "stream"] }
tokio = { version = "1.48.0", features = ["net", "time"] }
tokio-tungstenite = { version = "0.26.2", default-features = false, features = ["connect", "rustls-tls-webpki-roots"] }

[dev-dependencies]
orna-compiler = { path = "../orna-compiler" }
