[package]
name = "orna-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
orna-artifact = { path = "../orna-artifact" }
orna-core = { path = "../orna-core" }
orna-protocol = { path = "../orna-protocol" }
sha2 = "0.11.0"
orna-standard = { path = "../orna-standard" }
libloading = "0.9.0"
serde_json = "1.0.151"

[dev-dependencies]
orna-compiler = { path = "../orna-compiler" }
