[package]
name = "orna-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
orna-core = { path = "../orna-core" }
orna-standard = { path = "../orna-standard" }

[dev-dependencies]
proptest = { version = "1.11.0", default-features = false, features = ["std"] }
