name = "Orna"
grammar = "orna"
path_suffixes = ["orna"]
line_comments = ["--"]
block_comment = ["/*", "*/"]
brackets = [
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "{", end = "}", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false },
]
