id = "orna"
name = "Orna"
version = "0.1.0"
schema_version = 1
authors = ["OrnaDB"]
description = "Orna language support for Zed"
repository = "https://github.com/workingdir/ornadb"

[language_servers.orna-lsp]
name = "Orna Language Server"
languages = ["Orna"]
language_ids = { "Orna" = "orna" }

[grammars.orna]
repository = "https://github.com/workingdir/ornadb"
rev = "3ea2a9bf49cb6d3bfbd759c9711c4f556212aa59"
path = "editors/tree-sitter-orna"
