id = "orna"
name = "Orna"
version = "0.1.0"
schema_version = 1
authors = ["OrnaDB"]
description = "Orna language support for Zed"
repository = "https://github.com/workingdir/ornadb"

[language_servers.orna-lsp]
name = "Orna Language Server"
languages = ["Orna"]
language_ids = { "Orna" = "orna" }

[grammars.orna]
repository = "https://github.com/workingdir/ornadb"
rev = "c7df5e5edd75485b6790b611ebe1ac47ef0294ca"
path = "editors/tree-sitter-orna"
