[workspace]
members = ["crates/orna-artifact", "crates/orna-client", "crates/orna-compiler", "crates/orna-core", "crates/orna-lsp", "crates/orna-postgres", "crates/orna-protocol", "crates/orna-runtime-tty", "crates/orna-server", "crates/orna-sqlite", "crates/orna-standard", "crates/orna-storage", "crates/orna-syntax"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
license = "Apache-2.0"

[workspace.dependencies]
rowan = "0.16.1"
uuid = { version = "1.18.1", features = ["v4"] }
