(line_comment) @comment
(block_comment) @comment
(string) @string
(number) @number
(identifier) @variable
(kw_as) @keyword
(kw_assert) @keyword
(kw_base) @keyword
(kw_break) @keyword
(kw_case) @keyword
(kw_continue) @keyword
(kw_dim) @keyword
(kw_else) @keyword
(kw_enum) @keyword
(kw_false) @keyword
(kw_fn) @keyword
(kw_for) @keyword
(kw_if) @keyword
(kw_impl) @keyword
(kw_in) @keyword
(kw_let) @keyword
(kw_loop) @keyword
(kw_null) @keyword
(kw_offset) @keyword
(kw_affine) @keyword
(kw_protocol) @keyword
(kw_pub) @keyword
(kw_return) @keyword
(kw_self) @keyword
(kw_static) @keyword
(kw_table) @keyword
(kw_true) @keyword
(kw_type) @keyword
(kw_unit) @keyword
(kw_use) @keyword
(kw_while) @keyword
