; Orna Tree-sitter captures, generated from orna-syntax token metadata.
(comment) @comment
(string_literal) @string
(quoted_identifier) @identifier
(number) @number

[
    (kw_add)
    (kw_all)
    (kw_alter)
    (kw_and)
    (kw_as)
    (kw_asc)
    (kw_atomic)
    (kw_await)
    (kw_begin)
    (kw_between)
    (kw_bigint)
    (kw_binary)
    (kw_bool)
    (kw_boolean)
    (kw_by)
    (kw_bytes)
    (kw_call)
    (kw_capability)
    (kw_cascade)
    (kw_case)
    (kw_character)
    (kw_check)
    (kw_client)
    (kw_const)
    (kw_contract)
    (kw_create)
    (kw_cross)
    (kw_date)
    (kw_decimal)
    (kw_default)
    (kw_definer)
    (kw_delete)
    (kw_desc)
    (kw_disabled)
    (kw_distinct)
    (kw_documentation)
    (kw_drop)
    (kw_duration)
    (kw_else)
    (kw_elsif)
    (kw_end)
    (kw_enum)
    (kw_execute)
    (kw_exists)
    (kw_export)
    (kw_external)
    (kw_false)
    (kw_field)
    (kw_final)
    (kw_first)
    (kw_float)
    (kw_for)
    (kw_from)
    (kw_full)
    (kw_function)
    (kw_grant)
    (kw_group)
    (kw_having)
    (kw_if)
    (kw_ilike)
    (kw_immutable)
    (kw_in)
    (kw_inner)
    (kw_insert)
    (kw_inspect)
    (kw_int)
    (kw_integer)
    (kw_into)
    (kw_invoker)
    (kw_is)
    (kw_join)
    (kw_kernel)
    (kw_large)
    (kw_last)
    (kw_left)
    (kw_let)
    (kw_like)
    (kw_limit)
    (kw_list)
    (kw_local)
    (kw_loop)
    (kw_manual)
    (kw_map)
    (kw_not)
    (kw_null)
    (kw_nulls)
    (kw_object)
    (kw_offset)
    (kw_on)
    (kw_only)
    (kw_opaque)
    (kw_option)
    (kw_or)
    (kw_order)
    (kw_outer)
    (kw_persistable)
    (kw_prelude)
    (kw_primitive)
    (kw_read)
    (kw_ref)
    (kw_rename)
    (kw_requires)
    (kw_restrict)
    (kw_return)
    (kw_returning)
    (kw_returns)
    (kw_revoke)
    (kw_right)
    (kw_role)
    (kw_rows)
    (kw_runtime)
    (kw_schema)
    (kw_scope)
    (kw_sealed)
    (kw_security)
    (kw_select)
    (kw_server)
    (kw_session)
    (kw_set)
    (kw_stable)
    (kw_state)
    (kw_stream)
    (kw_table)
    (kw_text)
    (kw_then)
    (kw_time)
    (kw_timestamp)
    (kw_to)
    (kw_transaction)
    (kw_transient)
    (kw_true)
    (kw_type)
    (kw_union)
    (kw_unique)
    (kw_update)
    (kw_user)
    (kw_uuid)
    (kw_value)
    (kw_values)
    (kw_void)
    (kw_volatile)
    (kw_volatility)
    (kw_when)
    (kw_where)
    (kw_while)
] @keyword

(scalar_type) @type

[
    (comparison_operator)
    (additive_operator)
    (multiplicative_operator)
    (unary_operator)
    (assignment_operator)
    (arrow_operator)
    (client_comparison_operator)
    (client_additive_operator)
    (client_multiplicative_operator)
    (client_unary_operator)
    (client_concat_operator)
] @operator

[
    (lparen)
    (rparen)
    (lbracket)
    (rbracket)
    (lbrace)
    (rbrace)
    (comma)
    (semicolon)
    (dot)
    (colon)
    (question_mark)
] @punctuation

(qualified_name) @namespace
(type_spec (qualified_name) @type)
(create_schema_statement name: (qualified_name) @namespace)
(create_enum_type_statement name: (qualified_name) @type)
(create_object_type_statement name: (qualified_name) @type)
(create_value_type_statement name: (qualified_name) @type)
(export_type_statement name: (qualified_name) @type)
(create_server_function_statement name: (qualified_name) @function)
(create_client_function_statement name: (qualified_name) @function)
(create_external_client_function_statement name: (qualified_name) @function)
(select_statement table: (qualified_name) @type)
(insert_statement table: (qualified_name) @type)
(update_statement table: (qualified_name) @type)
(delete_statement table: (qualified_name) @type)
(call_statement callee: (invocation name: (qualified_name) @function))
(client_call_expression callee: (client_call_callee) @function)

(parameter_definition name: (identifier) @variable)
(field_definition name: (identifier) @property)
(table_column_definition name: (identifier) @property)
(record_field name: (identifier) @property)
(update_statement column: (identifier) @property)
(client_parameter_read) @variable
(client_field_path parameter: (_) @variable)
(client_field_path field: (_) @property)
(let_declaration name: (identifier) @variable)
(let_statement name: (identifier) @variable)
(const_declaration name: (identifier) @variable)
(state_declaration name: (identifier) @variable)
(client_local_declaration name: (_) @variable)
(client_let_statement name: (_) @variable)
(client_assignment_statement target: (_) @variable)
(client_state_declaration name: (_) @variable)
(for_statement name: (identifier) @variable)
(create_user_statement name: (identifier) @variable)
(create_role_statement name: (identifier) @variable)

; Keyword components may also appear as names. This alternative list is
; generated from the same keyword inventory as grammar.js.
(qualified_name [
            (kw_add)
            (kw_all)
            (kw_alter)
            (kw_and)
            (kw_as)
            (kw_asc)
            (kw_atomic)
            (kw_await)
            (kw_begin)
            (kw_between)
            (kw_bigint)
            (kw_binary)
            (kw_bool)
            (kw_boolean)
            (kw_by)
            (kw_bytes)
            (kw_call)
            (kw_capability)
            (kw_cascade)
            (kw_case)
            (kw_character)
            (kw_check)
            (kw_client)
            (kw_const)
            (kw_contract)
            (kw_create)
            (kw_cross)
            (kw_date)
            (kw_decimal)
            (kw_default)
            (kw_definer)
            (kw_delete)
            (kw_desc)
            (kw_disabled)
            (kw_distinct)
            (kw_documentation)
            (kw_drop)
            (kw_duration)
            (kw_else)
            (kw_elsif)
            (kw_end)
            (kw_enum)
            (kw_execute)
            (kw_exists)
            (kw_export)
            (kw_external)
            (kw_false)
            (kw_field)
            (kw_final)
            (kw_first)
            (kw_float)
            (kw_for)
            (kw_from)
            (kw_full)
            (kw_function)
            (kw_grant)
            (kw_group)
            (kw_having)
            (kw_if)
            (kw_ilike)
            (kw_immutable)
            (kw_in)
            (kw_inner)
            (kw_insert)
            (kw_inspect)
            (kw_int)
            (kw_integer)
            (kw_into)
            (kw_invoker)
            (kw_is)
            (kw_join)
            (kw_kernel)
            (kw_large)
            (kw_last)
            (kw_left)
            (kw_let)
            (kw_like)
            (kw_limit)
            (kw_list)
            (kw_local)
            (kw_loop)
            (kw_manual)
            (kw_map)
            (kw_not)
            (kw_null)
            (kw_nulls)
            (kw_object)
            (kw_offset)
            (kw_on)
            (kw_only)
            (kw_opaque)
            (kw_option)
            (kw_or)
            (kw_order)
            (kw_outer)
            (kw_persistable)
            (kw_prelude)
            (kw_primitive)
            (kw_read)
            (kw_ref)
            (kw_rename)
            (kw_requires)
            (kw_restrict)
            (kw_return)
            (kw_returning)
            (kw_returns)
            (kw_revoke)
            (kw_right)
            (kw_role)
            (kw_rows)
            (kw_runtime)
            (kw_schema)
            (kw_scope)
            (kw_sealed)
            (kw_security)
            (kw_select)
            (kw_server)
            (kw_session)
            (kw_set)
            (kw_stable)
            (kw_state)
            (kw_stream)
            (kw_table)
            (kw_text)
            (kw_then)
            (kw_time)
            (kw_timestamp)
            (kw_to)
            (kw_transaction)
            (kw_transient)
            (kw_true)
            (kw_type)
            (kw_union)
            (kw_unique)
            (kw_update)
            (kw_user)
            (kw_uuid)
            (kw_value)
            (kw_values)
            (kw_void)
            (kw_volatile)
            (kw_volatility)
            (kw_when)
            (kw_where)
            (kw_while)
] @namespace)
(type_spec (qualified_name [
            (kw_add)
            (kw_all)
            (kw_alter)
            (kw_and)
            (kw_as)
            (kw_asc)
            (kw_atomic)
            (kw_await)
            (kw_begin)
            (kw_between)
            (kw_bigint)
            (kw_binary)
            (kw_bool)
            (kw_boolean)
            (kw_by)
            (kw_bytes)
            (kw_call)
            (kw_capability)
            (kw_cascade)
            (kw_case)
            (kw_character)
            (kw_check)
            (kw_client)
            (kw_const)
            (kw_contract)
            (kw_create)
            (kw_cross)
            (kw_date)
            (kw_decimal)
            (kw_default)
            (kw_definer)
            (kw_delete)
            (kw_desc)
            (kw_disabled)
            (kw_distinct)
            (kw_documentation)
            (kw_drop)
            (kw_duration)
            (kw_else)
            (kw_elsif)
            (kw_end)
            (kw_enum)
            (kw_execute)
            (kw_exists)
            (kw_export)
            (kw_external)
            (kw_false)
            (kw_field)
            (kw_final)
            (kw_first)
            (kw_float)
            (kw_for)
            (kw_from)
            (kw_full)
            (kw_function)
            (kw_grant)
            (kw_group)
            (kw_having)
            (kw_if)
            (kw_ilike)
            (kw_immutable)
            (kw_in)
            (kw_inner)
            (kw_insert)
            (kw_inspect)
            (kw_int)
            (kw_integer)
            (kw_into)
            (kw_invoker)
            (kw_is)
            (kw_join)
            (kw_kernel)
            (kw_large)
            (kw_last)
            (kw_left)
            (kw_let)
            (kw_like)
            (kw_limit)
            (kw_list)
            (kw_local)
            (kw_loop)
            (kw_manual)
            (kw_map)
            (kw_not)
            (kw_null)
            (kw_nulls)
            (kw_object)
            (kw_offset)
            (kw_on)
            (kw_only)
            (kw_opaque)
            (kw_option)
            (kw_or)
            (kw_order)
            (kw_outer)
            (kw_persistable)
            (kw_prelude)
            (kw_primitive)
            (kw_read)
            (kw_ref)
            (kw_rename)
            (kw_requires)
            (kw_restrict)
            (kw_return)
            (kw_returning)
            (kw_returns)
            (kw_revoke)
            (kw_right)
            (kw_role)
            (kw_rows)
            (kw_runtime)
            (kw_schema)
            (kw_scope)
            (kw_sealed)
            (kw_security)
            (kw_select)
            (kw_server)
            (kw_session)
            (kw_set)
            (kw_stable)
            (kw_state)
            (kw_stream)
            (kw_table)
            (kw_text)
            (kw_then)
            (kw_time)
            (kw_timestamp)
            (kw_to)
            (kw_transaction)
            (kw_transient)
            (kw_true)
            (kw_type)
            (kw_union)
            (kw_unique)
            (kw_update)
            (kw_user)
            (kw_uuid)
            (kw_value)
            (kw_values)
            (kw_void)
            (kw_volatile)
            (kw_volatility)
            (kw_when)
            (kw_where)
            (kw_while)
] @type))
