#!/bin/bash
set -euo pipefail
export PATH=/usr/sbin:/usr/bin:/sbin:/bin

unset GLIBC_TUNABLES LD_AUDIT LD_DEBUG LD_DEBUG_OUTPUT LD_DYNAMIC_WEAK
unset LD_ASSUME_KERNEL LD_BIND_NOT LD_BIND_NOW LD_HWCAP_MASK LD_LIBRARY_PATH
unset LD_ORIGIN_PATH LD_PREFER_MAP_32BIT_EXEC LD_PRELOAD LD_PROFILE
unset LD_PROFILE_OUTPUT LD_SHOW_AUXV LD_TRACE_LOADED_OBJECTS
unset LD_TRACE_PRELINKING LD_USE_LOAD_BIAS LD_VERBOSE LD_WARN

case "${1-}:$#" in
    configure:2|abort-upgrade:2)
        ;;
    abort-remove:4|abort-deconfigure:4|abort-deconfigure:6)
        [ "${2-}" = in-favour ] || exit 1
        ;;
    *)
        exit 1
        ;;
esac

/usr/bin/env -i /usr/bin/systemd-sysusers /usr/lib/sysusers.d/orna.conf
/usr/bin/env -i /usr/bin/systemd-tmpfiles --create /usr/lib/tmpfiles.d/orna.conf
if [ -d /run/systemd/system ]; then
    /usr/bin/env -i /usr/bin/systemctl daemon-reload
fi
[ -x /usr/bin/orna ] || exit 1
exec /usr/bin/env -i ORNA_PACKAGE_MAINTENANCE=complete /usr/bin/orna
