#!/bin/sh
set -eu

unset GLIBC_TUNABLES LD_AUDIT LD_DEBUG LD_DEBUG_OUTPUT LD_DYNAMIC_WEAK
unset LD_ASSUME_KERNEL LD_BIND_NOT LD_BIND_NOW LD_HWCAP_MASK LD_LIBRARY_PATH
unset LD_ORIGIN_PATH LD_PREFER_MAP_32BIT_EXEC LD_PRELOAD LD_PROFILE
unset LD_PROFILE_OUTPUT LD_SHOW_AUXV LD_TRACE_LOADED_OBJECTS
unset LD_TRACE_PRELINKING LD_USE_LOAD_BIAS LD_VERBOSE LD_WARN

case "${1-}:$#" in
    install:1|install:3)
        exit 0
        ;;
    upgrade:3)
        set +e
        /usr/bin/env -i /usr/bin/dpkg --compare-versions "$3" lt "$2"
        comparison=$?
        set -e
        case "$comparison" in
            0)
                printf '%s\n' 'orna: package downgrade is not supported' >&2
                exit 1
                ;;
            1)
                ;;
            *)
                exit 1
                ;;
        esac
        ;;
    *)
        exit 1
        ;;
esac

[ -x /usr/bin/orna ] || exit 1
exec /usr/bin/env -i ORNA_PACKAGE_MAINTENANCE=begin /usr/bin/orna
