#!/bin/bash
set -euo pipefail
export PATH=/usr/sbin:/usr/bin:/sbin:/bin

unset GLIBC_TUNABLES LD_AUDIT LD_DEBUG LD_DEBUG_OUTPUT LD_DYNAMIC_WEAK
unset LD_ASSUME_KERNEL LD_BIND_NOT LD_BIND_NOW LD_HWCAP_MASK LD_LIBRARY_PATH
unset LD_ORIGIN_PATH LD_PREFER_MAP_32BIT_EXEC LD_PRELOAD LD_PROFILE
unset LD_PROFILE_OUTPUT LD_SHOW_AUXV LD_TRACE_LOADED_OBJECTS
unset LD_TRACE_PRELINKING LD_USE_LOAD_BIAS LD_VERBOSE LD_WARN

case "${1-}:$#" in
    upgrade:2)
        exit 0
        ;;
    remove:1|failed-upgrade:2)
        ;;
    deconfigure:4|deconfigure:6)
        [ "${2-}" = in-favour ] || exit 1
        ;;
    *)
        exit 1
        ;;
esac

[ -x /usr/bin/orna ] || exit 1
exec /usr/bin/env -i ORNA_PACKAGE_MAINTENANCE=begin /usr/bin/orna
