[package]
name = "orna-postgres"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
build = "build.rs"

[features]
embedded = []
test-hooks = ["orna-kernel-postgres/test-hooks"]

[dependencies]
orna-kernel-postgres = { path = "../orna-kernel-postgres" }
