// Generated from orna-syntax-v1; keywords are the ORNA-LEX-007 inventory.
const KEYWORDS = [
    'as',
    'assert',
    'base',
    'break',
    'case',
    'continue',
    'dim',
    'else',
    'enum',
    'false',
    'fn',
    'for',
    'if',
    'impl',
    'in',
    'let',
    'loop',
    'null',
    'offset',
    'affine',
    'protocol',
    'pub',
    'return',
    'self',
    'static',
    'table',
    'true',
    'type',
    'unit',
    'use',
    'while',
];
const keywordRules = {};
for (const word of KEYWORDS) keywordRules['kw_' + word] = ($) => word;

module.exports = grammar({
  name: 'orna',
  extras: ($) => [/\s/, $.line_comment, $.block_comment],
  word: ($) => $.identifier,
  rules: Object.assign({
    source_file: ($) => repeat(choice($._declaration, $._statement)),
    _declaration: ($) => choice($.function_declaration, $.type_declaration, $.enum_declaration,
      $.table_declaration, $.protocol_declaration, $.unit_declaration, $.use_declaration,
      $.implementation_declaration),
    function_declaration: ($) => seq(optional($.kw_pub), $.kw_fn, field('name', $.identifier),
      optional($.generic_parameters), $.parameter_list, optional(seq(':', $.type)), '=', $.expression, ';'),
    type_declaration: ($) => seq(optional($.kw_pub), $.kw_type, field('name', $.identifier), '=', $.type, ';'),
    enum_declaration: ($) => seq(optional($.kw_pub), $.kw_enum, field('name', $.identifier), '{',
      commaSep1($.enum_variant), optional(','), '}'),
    enum_variant: ($) => seq($.identifier, optional($.record_type)),
    record_type: ($) => seq('{', commaSep1(seq($.identifier, ':', $.type)), optional(','), '}'),
    table_declaration: ($) => seq(optional($.kw_pub), $.kw_table, field('name', $.identifier),
      optional($.parameter_list), '{', repeat(choice($.field_declaration, $.assertion)), '}'),
    field_declaration: ($) => seq($.identifier, ':', $.type, optional(seq('=', $.expression)), ','),
    assertion: ($) => seq($.kw_assert, $.expression, ';'),
    protocol_declaration: ($) => seq(optional($.kw_pub), $.kw_protocol, $.identifier,
      '{', repeat($.function_signature), '}'),
    function_signature: ($) => seq($.kw_fn, $.identifier, $.parameter_list, optional(seq(':', $.type)), ';'),
    unit_declaration: ($) => seq(optional($.kw_pub), $.kw_unit, $.identifier, '=', $.expression, ';'),
    use_declaration: ($) => seq($.kw_use, $.qualified_name, optional(seq($.kw_as, $.identifier)), ';'),
    implementation_declaration: ($) => seq($.kw_impl, $.type, '{', repeat($.function_declaration), '}'),
    generic_parameters: ($) => seq('<', commaSep1($.identifier), optional(','), '>'),
    parameter_list: ($) => seq('(', commaSep($.parameter), ')'),
    parameter: ($) => seq($.identifier, ':', $.type, optional(seq('=', $.expression))),
    type: ($) => choice($.qualified_name, seq($.identifier, '<', commaSep1($.type), '>'),
      seq('[', $.type, ']'), seq('(', commaSep($.type), ')', '->', $.type)),
    qualified_name: ($) => seq($.identifier, repeat(seq('.', $.identifier))),
    _statement: ($) => choice($.let_statement, $.return_statement, $.while_statement, $.expression_statement),
    let_statement: ($) => seq($.kw_let, $.identifier, optional(seq(':', $.type)), '=', $.expression, ';'),
    return_statement: ($) => seq($.kw_return, optional($.expression), ';'),
    while_statement: ($) => seq($.kw_while, $.expression, $.block),
    expression_statement: ($) => seq($.expression, ';'),
    block: ($) => seq('{', repeat($._statement), '}'),
    expression: ($) => choice($.literal, $.qualified_name, $.call_expression, $.binary_expression,
      $.unary_expression, $.lambda_expression, $.parenthesized_expression, $.record_expression),
    call_expression: ($) => prec(2, seq($.expression, '(', commaSep($.expression), ')')),
    binary_expression: ($) => prec.left(1, seq($.expression, $._operator, $.expression)),
    unary_expression: ($) => prec(3, seq(choice('!', '-', '+'), $.expression)),
    lambda_expression: ($) => prec.right(0, seq('|', commaSep($.identifier), '|', $.expression)),
    parenthesized_expression: ($) => seq('(', $.expression, ')'),
    record_expression: ($) => seq('{', commaSep(seq($.identifier, ':', $.expression)), '}'),
    literal: ($) => choice($.string, $.number, $.kw_true, $.kw_false, $.kw_null),
    string: ($) => seq('"', repeat(choice(/[^"\\]+/, /\\./, seq('{', $.expression, '}'))), '"'),
    number: ($) => /[0-9]+(?:\.[0-9]+)?/,
    identifier: ($) => /[_\p{L}][_\p{L}\p{N}]*/,
    line_comment: ($) => token(seq('//', /[^\n\r]*/)),
    block_comment: ($) => seq('/*', repeat(choice($.block_comment, /[^*]+|\*+[^*/]/)), '*/'),
    _operator: ($) => choice('..=', '=>', '==', '!=', '<=', '>=', '??', '|?', '&&', '||', '+=', '-=', '*=', '/=', '..', '|', '!', '=', '<', '>', '+', '-', '*', '/', '%', '^', '?'),
  }, keywordRules),
});

function commaSep(rule) { return optional(commaSep1(rule)); }
function commaSep1(rule) { return seq(rule, repeat(seq(',', rule))); }
