//! Public request/completion binding for one client-side Inspector lifecycle.
//!
//! [`ClientInspectLifecycle`] owns the epoch
//! state. This module is the small host-facing seam that makes that state
//! useful: requests are admitted only for the live epoch, and a completion is
//! published only while the request and its exact epoch are still current.

use orna_core::{InvocationId, system::SYS_INSPECT_INVOCATION_TYPE_ID, value::RuntimeValue};

use crate::{
    ClientInspectError, ClientInspectLifecycle, ClientInspectLifecycleState,
    ClientInspectOperation, ClientInspectRequest, InspectEpochBinding, InspectFreezeToken,
    InspectLifecycleError,
};

/// One Inspector request admitted by a [`ClientInspectLifecycleSession`].
///
/// The request id is generated by the client and is not an authority token.
/// It exists solely to prevent a completion for an older request from being
/// published after a refresh, cancellation, or a prior completion.
#[derive(Clone, Debug, PartialEq)]
pub struct ClientInspectLifecycleRequest {
    request_id: InvocationId,
    request: ClientInspectRequest,
    binding: InspectEpochBinding,
}

impl ClientInspectLifecycleRequest {
    fn new(request: ClientInspectRequest, binding: InspectEpochBinding) -> Self {
        Self {
            request_id: InvocationId::new(),
            request,
            binding,
        }
    }

    /// Returns the client-generated request identity.
    pub const fn request_id(&self) -> InvocationId {
        self.request_id
    }

    /// Returns the typed request sent to the installed Inspector provider.
    pub const fn request(&self) -> &ClientInspectRequest {
        &self.request
    }

    /// Returns the exact epoch evidence pinned to this request.
    pub const fn binding(&self) -> InspectEpochBinding {
        self.binding
    }

    /// Returns the sealed Inspector operation carried by the request.
    pub const fn operation(&self) -> &ClientInspectOperation {
        self.request.operation()
    }

    /// Creates a successful completion carrying this request's exact binding.
    pub fn ready(&self, value: RuntimeValue) -> ClientInspectLifecycleCompletion {
        ClientInspectLifecycleCompletion::ready(self.request_id, self.binding, value)
    }

    /// Creates a failed terminal completion carrying this request's exact
    /// binding. The session normalises the provider code before exposing it.
    pub fn failed(&self, code: impl Into<String>) -> ClientInspectLifecycleCompletion {
        ClientInspectLifecycleCompletion::failed(self.request_id, self.binding, code)
    }
}

/// A terminal result returned by an Inspector provider.
#[derive(Clone, Debug, PartialEq)]
pub struct ClientInspectLifecycleCompletion {
    request_id: InvocationId,
    binding: InspectEpochBinding,
    result: Result<RuntimeValue, String>,
}

impl ClientInspectLifecycleCompletion {
    /// Creates a successful completion for a request identity and epoch.
    pub fn ready(
        request_id: InvocationId,
        binding: InspectEpochBinding,
        value: RuntimeValue,
    ) -> Self {
        Self {
            request_id,
            binding,
            result: Ok(value),
        }
    }

    /// Creates a failed completion for a request identity and epoch.
    pub fn failed(
        request_id: InvocationId,
        binding: InspectEpochBinding,
        code: impl Into<String>,
    ) -> Self {
        let code = code.into();
        Self {
            request_id,
            binding,
            result: Err(crate::execution::stable_inspect_provider_error(&code)),
        }
    }

    /// Returns the request identity that produced this completion.
    pub const fn request_id(&self) -> InvocationId {
        self.request_id
    }

    /// Returns the epoch evidence returned with this completion.
    pub const fn binding(&self) -> InspectEpochBinding {
        self.binding
    }

    /// Returns the successful value, if this is a successful completion.
    pub fn value(&self) -> Option<&RuntimeValue> {
        self.result.as_ref().ok()
    }

    /// Returns the provider failure code, if this is a failed completion.
    pub fn failure_code(&self) -> Option<&str> {
        self.result.as_ref().err().map(String::as_str)
    }
}

/// The host-facing Inspector lifecycle seam.
///
/// A session deliberately tracks only one currently publishable request. A
/// later request supersedes an earlier one; the older request remains a valid
/// value for transport bookkeeping, but its completion can no longer publish.
#[derive(Clone, Debug, PartialEq)]
pub struct ClientInspectLifecycleSession {
    lifecycle: ClientInspectLifecycle,
    pending_request_id: Option<InvocationId>,
}

impl ClientInspectLifecycleSession {
    /// Creates an active session for one Inspector epoch.
    pub fn new(binding: InspectEpochBinding) -> Self {
        Self {
            lifecycle: ClientInspectLifecycle::new(binding),
            pending_request_id: None,
        }
    }

    /// Returns the underlying lifecycle state.
    pub const fn lifecycle(&self) -> &ClientInspectLifecycle {
        &self.lifecycle
    }

    /// Returns the current epoch binding.
    pub const fn binding(&self) -> InspectEpochBinding {
        self.lifecycle.binding()
    }

    /// Returns the current lifecycle state.
    pub const fn state(&self) -> ClientInspectLifecycleState {
        self.lifecycle.state()
    }

    /// Freezes the session and returns its exact transient token.
    pub fn freeze(&mut self) -> Result<InspectFreezeToken, ClientInspectError> {
        self.lifecycle.freeze().map_err(Into::into)
    }

    /// Resumes the session with its exact live token.
    pub fn resume(&mut self, token: InspectFreezeToken) -> Result<(), ClientInspectError> {
        self.lifecycle.resume(token).map_err(Into::into)
    }

    /// Replaces the current epoch with a newer binding.
    ///
    /// A successful replacement invalidates the currently pending request.
    /// Rejected stale, principal/revision-changing, or enclosing-execution
    /// replacements leave the session untouched; a refresh may carry a new
    /// server snapshot identity.
    pub fn replace_epoch(
        &mut self,
        binding: InspectEpochBinding,
    ) -> Result<(), ClientInspectError> {
        validate_lifecycle_state(&self.lifecycle).map_err(ClientInspectError::from)?;
        let current = self.lifecycle.binding();
        let replaces_epoch = binding.generation() > current.generation();
        if replaces_epoch {
            // A refresh may capture a new server snapshot identity, but the
            // active session cannot change its principal, revision, enclosing
            // client execution, target, observer lineage, or projection set.
            if binding.principal() != current.principal() {
                return Err(InspectLifecycleError::PrincipalMismatch.into());
            }
            if binding.revision() != current.revision() {
                return Err(InspectLifecycleError::RevisionMismatch {
                    expected: current.revision(),
                    actual: binding.revision(),
                }
                .into());
            }
            if binding.client_epoch_id() != current.client_epoch_id()
                || binding.target_invocation_id() != current.target_invocation_id()
                || binding.observer_root_invocation_id() != current.observer_root_invocation_id()
                || binding.observer_parent_invocation_id()
                    != current.observer_parent_invocation_id()
                || binding.projection_versions() != current.projection_versions()
            {
                return Err(InspectLifecycleError::EpochMismatch.into());
            }
        }
        self.lifecycle
            .replace_epoch(binding)
            .map_err(ClientInspectError::from)?;
        if replaces_epoch {
            self.pending_request_id = None;
        }
        Ok(())
    }
    /// Cancels the session and invalidates any in-flight completion.
    pub fn cancel(&mut self) {
        self.lifecycle.cancel();
        self.pending_request_id = None;
    }

    /// Closes the session and invalidates any in-flight completion.
    pub fn shutdown(&mut self) {
        self.lifecycle.shutdown();
        self.pending_request_id = None;
    }

    /// Admits a typed Inspector provider request to this lifecycle.
    ///
    /// The request's client epoch, revision, observer lineage, and target
    /// evidence must agree with the supplied epoch evidence. The lifecycle
    /// itself additionally checks generation, principal, revision, and all
    /// other exact binding fields.
    pub fn begin_request(
        &mut self,
        request: ClientInspectRequest,
        binding: InspectEpochBinding,
    ) -> Result<ClientInspectLifecycleRequest, ClientInspectError> {
        self.validate_request(&request, binding)?;
        let request = ClientInspectLifecycleRequest::new(request, binding);
        self.pending_request_id = Some(request.request_id());
        Ok(request)
    }

    /// Validates a request without making it publishable.
    pub fn validate_request(
        &self,
        request: &ClientInspectRequest,
        binding: InspectEpochBinding,
    ) -> Result<(), ClientInspectError> {
        validate_lifecycle_state(&self.lifecycle)?;
        binding
            .validate_against(&self.lifecycle.binding())
            .map_err(ClientInspectError::from)?;
        validate_request_binding(request, binding)
    }

    /// Validates a completion without consuming or publishing it.
    pub fn validate_completion(
        &self,
        completion: &ClientInspectLifecycleCompletion,
    ) -> Result<(), ClientInspectError> {
        self.lifecycle
            .validate_completion(&completion.binding)
            .map_err(ClientInspectError::from)?;
        if self.pending_request_id != Some(completion.request_id) {
            return Err(stale_completion_error());
        }
        Ok(())
    }

    /// Publishes a valid completion and returns its value.
    ///
    /// Invalid, stale, cancelled, closed, or mismatched completions return a
    /// stable [`ClientInspectError`] and leave the session unchanged. A valid
    /// terminal completion clears the pending request before returning;
    /// therefore it cannot be published a second time.
    pub fn publish_completion(
        &mut self,
        completion: ClientInspectLifecycleCompletion,
    ) -> Result<RuntimeValue, ClientInspectError> {
        self.validate_completion(&completion)?;
        self.pending_request_id = None;
        match completion.result {
            Ok(value) => Ok(value),
            Err(code) => Err(ClientInspectError::Failed(
                crate::execution::stable_inspect_provider_error(&code),
            )),
        }
    }
}

fn validate_lifecycle_state(
    lifecycle: &ClientInspectLifecycle,
) -> Result<(), InspectLifecycleError> {
    if lifecycle.is_cancelled() {
        return Err(InspectLifecycleError::Cancelled);
    }
    if lifecycle.is_closed() {
        return Err(InspectLifecycleError::Closed);
    }
    Ok(())
}

fn stale_completion_error() -> ClientInspectError {
    ClientInspectError::Failed("inspect.stale_epoch".to_owned())
}

fn validate_request_binding(
    request: &ClientInspectRequest,
    binding: InspectEpochBinding,
) -> Result<(), ClientInspectError> {
    if request.client_epoch_id().invocation_id() != binding.client_epoch_id()
        || request.observer_root_invocation_id() != binding.observer_root_invocation_id()
        || request.observer_parent_invocation_id() != binding.observer_parent_invocation_id()
    {
        return Err(InspectLifecycleError::EpochMismatch.into());
    }
    if request.pair() != binding.revision() {
        return Err(InspectLifecycleError::RevisionMismatch {
            expected: binding.revision(),
            actual: request.pair(),
        }
        .into());
    }
    if let Some(target) = request.target_invocation_id()
        && target != binding.target_invocation_id()
    {
        return Err(InspectLifecycleError::EpochMismatch.into());
    }
    match request.operation() {
        ClientInspectOperation::Snapshot { target } => {
            let target = invocation_target(target).ok_or(ClientInspectError::InvalidTarget)?;
            if request.target_invocation_id() != Some(target) {
                return Err(ClientInspectError::InvalidTarget);
            }
            if target != binding.target_invocation_id() {
                return Err(InspectLifecycleError::EpochMismatch.into());
            }
        }
        ClientInspectOperation::Projection { .. } => {
            if request.target_invocation_id().is_none() {
                return Err(ClientInspectError::InvalidSnapshot);
            }
        }
    }
    Ok(())
}

fn invocation_target(value: &RuntimeValue) -> Option<InvocationId> {
    let RuntimeValue::Reference { target, object } = value else {
        return None;
    };
    if *target != SYS_INSPECT_INVOCATION_TYPE_ID || object.to_bytes() == [0; 16] {
        return None;
    }
    Some(InvocationId::from_bytes(object.to_bytes()))
}

impl From<InspectLifecycleError> for ClientInspectError {
    fn from(error: InspectLifecycleError) -> Self {
        Self::Failed(error.code().to_owned())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ClientExecutionContext;
    use orna_core::{
        CatalogueRevisionId, FunctionId, FunctionRevisionId, ObjectId, PrincipalId,
        SourceRevisionId, revision::RevisionPair,
    };

    fn invocation_id(byte: u8) -> InvocationId {
        InvocationId::from_bytes([byte; 16])
    }

    fn principal_id(byte: u8) -> PrincipalId {
        PrincipalId::from_bytes([byte; 16])
    }

    fn revision_pair(byte: u8) -> RevisionPair {
        RevisionPair::new(
            SourceRevisionId::from_bytes([byte; 16]),
            CatalogueRevisionId::from_bytes([byte; 16]),
        )
    }

    fn binding(generation: u64) -> InspectEpochBinding {
        InspectEpochBinding::new(
            invocation_id(1),
            2,
            invocation_id(3),
            principal_id(4),
            revision_pair(5),
            invocation_id(1),
            invocation_id(1),
            crate::InspectProjectionVersions::v1(),
            generation,
        )
    }

    fn context() -> ClientExecutionContext {
        ClientExecutionContext {
            pair: revision_pair(5),
            function: FunctionId::from_bytes([8; 16]),
            function_revision: FunctionRevisionId::from_bytes([9; 16]),
            parent_invocation_id: invocation_id(1),
            observer_lineage: None,
        }
    }

    fn request() -> ClientInspectRequest {
        ClientInspectRequest::new(
            context(),
            ClientInspectOperation::Snapshot {
                target: RuntimeValue::Reference {
                    target: SYS_INSPECT_INVOCATION_TYPE_ID,
                    object: ObjectId::from_bytes([3; 16]),
                },
            },
        )
    }

    #[test]
    fn request_and_completion_are_gated_by_the_live_epoch() {
        let current = binding(1);
        let mut session = ClientInspectLifecycleSession::new(current);
        let operation = session
            .begin_request(request(), current)
            .expect("matching Inspector request is admitted");
        assert_eq!(session.replace_epoch(current), Ok(()));
        let completion = operation.ready(RuntimeValue::Boolean(true));

        assert_eq!(session.validate_completion(&completion), Ok(()));
        assert_eq!(
            session.publish_completion(completion.clone()),
            Ok(RuntimeValue::Boolean(true))
        );
        assert_eq!(
            session.validate_completion(&completion),
            Err(ClientInspectError::Failed("inspect.stale_epoch".to_owned()))
        );
    }

    #[test]
    fn delayed_completion_after_cancel_is_rejected_without_publication() {
        let current = binding(1);
        let mut session = ClientInspectLifecycleSession::new(current);
        let operation = session
            .begin_request(request(), current)
            .expect("matching Inspector request is admitted");
        let completion = operation.ready(RuntimeValue::Boolean(true));

        session.cancel();
        assert_eq!(
            session.publish_completion(completion),
            Err(ClientInspectError::Failed("inspect.cancelled".to_owned()))
        );
        assert!(session.lifecycle().is_cancelled());
    }

    #[test]
    fn provider_failure_codes_are_stable_before_publication() {
        let current = binding(1);
        let mut session = ClientInspectLifecycleSession::new(current);
        let operation = session
            .begin_request(request(), current)
            .expect("matching Inspector request is admitted");
        let completion = operation.failed("provider.secret-details");

        assert_eq!(completion.failure_code(), Some("inspect.projection_failed"));
        assert_eq!(
            session.publish_completion(completion),
            Err(ClientInspectError::Failed(
                "inspect.projection_failed".to_owned()
            ))
        );
    }

    #[test]
    fn public_projection_factory_binds_each_accepted_projection_to_snapshot_target() {
        let current = binding(1);
        let mut session = ClientInspectLifecycleSession::new(current);
        let projections = [
            crate::InspectProjection::InvocationNodes,
            crate::InspectProjection::Calls,
            crate::InspectProjection::Resources,
            crate::InspectProjection::StateCells,
            crate::InspectProjection::UiNodes,
            crate::InspectProjection::PresentationCandidates,
            crate::InspectProjection::RuntimeBindings,
            crate::InspectProjection::SecurityDecisions,
        ];

        for projection in projections {
            let request = ClientInspectRequest::projection(
                context(),
                projection,
                RuntimeValue::Boolean(true),
                current.target_invocation_id(),
            )
            .expect("public projection factory accepts a checked target");
            assert_eq!(request.context(), context());
            assert_eq!(
                request.target_invocation_id(),
                Some(current.target_invocation_id())
            );
            let operation = session
                .begin_request(request, current)
                .expect("matching projection request is admitted");
            assert_eq!(operation.operation().projection(), Some(projection));
            assert_eq!(
                session.publish_completion(operation.ready(RuntimeValue::Boolean(true))),
                Ok(RuntimeValue::Boolean(true))
            );
        }
    }

    #[test]
    fn public_projection_factory_rejects_absent_target_identity() {
        assert_eq!(
            ClientInspectRequest::projection(
                context(),
                crate::InspectProjection::Calls,
                RuntimeValue::Boolean(true),
                InvocationId::from_bytes([0; 16]),
            ),
            Err(ClientInspectError::InvalidTarget)
        );
    }

    #[test]
    fn public_projection_factory_target_mismatch_fails_before_pending() {
        let current = binding(1);
        let mut session = ClientInspectLifecycleSession::new(current);
        let request = ClientInspectRequest::projection(
            context(),
            crate::InspectProjection::Calls,
            RuntimeValue::Boolean(true),
            invocation_id(8),
        )
        .expect("nonzero projection target is constructible");

        assert_eq!(
            session.begin_request(request, current),
            Err(ClientInspectError::Failed(
                "inspect.epoch_mismatch".to_owned(),
            ))
        );
        assert_eq!(session.pending_request_id, None);
    }

    #[test]
    fn malformed_and_targetless_requests_are_rejected_before_pending() {
        let current = binding(1);
        let mut session = ClientInspectLifecycleSession::new(current);
        let malformed = ClientInspectRequest::new(
            context(),
            ClientInspectOperation::Snapshot {
                target: RuntimeValue::Boolean(true),
            },
        );
        assert_eq!(
            session.begin_request(malformed, current),
            Err(ClientInspectError::InvalidTarget)
        );

        let targetless_projection = ClientInspectRequest::new(
            context(),
            ClientInspectOperation::Projection {
                projection: crate::InspectProjection::Calls,
                snapshot: RuntimeValue::Boolean(true),
            },
        );
        assert_eq!(
            session.begin_request(targetless_projection, current),
            Err(ClientInspectError::InvalidSnapshot)
        );
        assert_eq!(session.pending_request_id, None);
    }
    #[test]
    fn request_target_mismatch_is_rejected_before_pending() {
        let current = binding(1);
        let mut session = ClientInspectLifecycleSession::new(current);
        let mismatched = ClientInspectRequest::new(
            context(),
            ClientInspectOperation::Snapshot {
                target: RuntimeValue::Reference {
                    target: SYS_INSPECT_INVOCATION_TYPE_ID,
                    object: ObjectId::from_bytes([8; 16]),
                },
            },
        );

        assert_eq!(
            session.begin_request(mismatched, current),
            Err(ClientInspectError::Failed(
                "inspect.epoch_mismatch".to_owned(),
            ))
        );
        assert_eq!(session.pending_request_id, None);
    }

    #[test]
    fn stale_future_principal_and_revision_completions_keep_the_request_pending() {
        let current = binding(2);
        let mut session = ClientInspectLifecycleSession::new(current);
        let operation = session
            .begin_request(request(), current)
            .expect("matching Inspector request is admitted");

        let stale = ClientInspectLifecycleCompletion::ready(
            operation.request_id(),
            binding(1),
            RuntimeValue::Boolean(true),
        );
        assert_eq!(
            session.publish_completion(stale),
            Err(ClientInspectError::Failed("inspect.stale_epoch".to_owned()))
        );

        let future = ClientInspectLifecycleCompletion::ready(
            operation.request_id(),
            binding(3),
            RuntimeValue::Boolean(true),
        );
        assert_eq!(
            session.publish_completion(future),
            Err(ClientInspectError::Failed(
                "inspect.future_epoch".to_owned()
            ))
        );

        let principal = InspectEpochBinding::new(
            current.client_epoch_id(),
            current.server_epoch_id(),
            current.target_invocation_id(),
            principal_id(8),
            current.revision(),
            current.observer_root_invocation_id(),
            current.observer_parent_invocation_id(),
            current.projection_versions(),
            current.generation(),
        );
        assert_eq!(
            session.publish_completion(ClientInspectLifecycleCompletion::ready(
                operation.request_id(),
                principal,
                RuntimeValue::Boolean(true),
            )),
            Err(ClientInspectError::Failed(
                "inspect.epoch_mismatch".to_owned()
            ))
        );

        let revision = InspectEpochBinding::new(
            current.client_epoch_id(),
            current.server_epoch_id(),
            current.target_invocation_id(),
            current.principal(),
            revision_pair(9),
            current.observer_root_invocation_id(),
            current.observer_parent_invocation_id(),
            current.projection_versions(),
            current.generation(),
        );
        assert_eq!(
            session.publish_completion(ClientInspectLifecycleCompletion::ready(
                operation.request_id(),
                revision,
                RuntimeValue::Boolean(true),
            )),
            Err(ClientInspectError::Failed(
                "inspect.epoch_mismatch".to_owned()
            ))
        );

        assert_eq!(session.pending_request_id, Some(operation.request_id()));
    }

    #[test]
    fn higher_generation_replacement_preserves_authority_and_refreshes_identity() {
        let current = binding(1);
        let mut session = ClientInspectLifecycleSession::new(current);
        let operation = session
            .begin_request(request(), current)
            .expect("matching Inspector request is admitted");

        let principal = InspectEpochBinding::new(
            current.client_epoch_id(),
            current.server_epoch_id(),
            current.target_invocation_id(),
            principal_id(8),
            current.revision(),
            current.observer_root_invocation_id(),
            current.observer_parent_invocation_id(),
            current.projection_versions(),
            2,
        );
        assert_eq!(
            session.replace_epoch(principal),
            Err(ClientInspectError::Failed(
                "inspect.epoch_mismatch".to_owned()
            ))
        );
        assert_eq!(session.binding(), current);
        assert_eq!(session.pending_request_id, Some(operation.request_id()));

        let revision = InspectEpochBinding::new(
            current.client_epoch_id(),
            current.server_epoch_id(),
            current.target_invocation_id(),
            current.principal(),
            revision_pair(9),
            current.observer_root_invocation_id(),
            current.observer_parent_invocation_id(),
            current.projection_versions(),
            2,
        );
        assert_eq!(
            session.replace_epoch(revision),
            Err(ClientInspectError::Failed(
                "inspect.epoch_mismatch".to_owned()
            ))
        );
        assert_eq!(session.binding(), current);
        assert_eq!(session.pending_request_id, Some(operation.request_id()));

        let foreign_execution = InspectEpochBinding::new(
            invocation_id(9),
            current.server_epoch_id(),
            current.target_invocation_id(),
            current.principal(),
            current.revision(),
            current.observer_root_invocation_id(),
            current.observer_parent_invocation_id(),
            current.projection_versions(),
            2,
        );
        assert_eq!(
            session.replace_epoch(foreign_execution),
            Err(ClientInspectError::Failed(
                "inspect.epoch_mismatch".to_owned()
            ))
        );
        assert_eq!(session.binding(), current);
        assert_eq!(session.pending_request_id, Some(operation.request_id()));

        let replacement = binding(2);
        assert_eq!(session.replace_epoch(replacement), Ok(()));
        assert_eq!(session.binding(), replacement);
        assert_eq!(session.pending_request_id, None);
        assert_eq!(
            session.publish_completion(operation.ready(RuntimeValue::Boolean(true))),
            Err(ClientInspectError::Failed("inspect.stale_epoch".to_owned()))
        );

        let refreshed = InspectEpochBinding::new(
            replacement.client_epoch_id(),
            replacement.server_epoch_id() + 1,
            replacement.target_invocation_id(),
            replacement.principal(),
            replacement.revision(),
            replacement.observer_root_invocation_id(),
            replacement.observer_parent_invocation_id(),
            replacement.projection_versions(),
            3,
        );
        assert_eq!(session.replace_epoch(refreshed), Ok(()));
        assert_eq!(session.binding(), refreshed);
    }

    #[test]
    fn freeze_resume_and_shutdown_preserve_token_and_close_late_results() {
        let current = binding(1);
        let mut session = ClientInspectLifecycleSession::new(current);
        let operation = session
            .begin_request(request(), current)
            .expect("matching Inspector request is admitted");
        let completion = operation.ready(RuntimeValue::Boolean(true));
        let token = session.freeze().expect("active session freezes");
        assert_eq!(session.resume(token), Ok(()));

        session.shutdown();
        assert_eq!(
            session.publish_completion(completion),
            Err(ClientInspectError::Failed("inspect.closed".to_owned()))
        );
        assert!(session.lifecycle().is_closed());
    }

    #[test]
    fn request_revision_mismatch_is_rejected_before_it_becomes_pending() {
        let current = binding(1);
        let mut session = ClientInspectLifecycleSession::new(current);
        let mut wrong_context = context();
        wrong_context.pair = revision_pair(9);
        let request = ClientInspectRequest::new(
            wrong_context,
            ClientInspectOperation::Snapshot {
                target: RuntimeValue::Reference {
                    target: SYS_INSPECT_INVOCATION_TYPE_ID,
                    object: ObjectId::from_bytes([3; 16]),
                },
            },
        );

        assert_eq!(
            session.begin_request(request, current),
            Err(ClientInspectError::Failed(
                "inspect.epoch_mismatch".to_owned()
            ))
        );
        assert_eq!(session.pending_request_id, None);
    }
}
