[package]
name = "orna-kernel-postgres"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
orna-artifact = { path = "../orna-artifact" }
orna-core = { path = "../orna-core" }
sha2 = "0.11.0"
tokio = { version = "1.53.1", features = ["net", "rt"] }
tokio-postgres = "0.7.18"

[dev-dependencies]
orna-compiler = { path = "../orna-compiler" }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "sync"] }
