#!/usr/bin/env python3
"""Pin every regular file in crate-local fixture trees by SHA-256."""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys
from collections.abc import Mapping
from pathlib import Path, PurePosixPath

WORKSPACE_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = Path(__file__).with_name("fixture-manifest.sha256")
MANIFEST_LABEL = MANIFEST_PATH.relative_to(WORKSPACE_ROOT).as_posix()
MANIFEST_HEADER = (
    "# Generated by scripts/check_fixture_manifest.py --update.\n"
    "# SHA-256  workspace-relative fixture path\n"
)
HASH_PATTERN = re.compile(r"[0-9a-f]{64}")
IGNORED_WORKSPACE_DIRS = {".git", ".beads", ".scratch", "node_modules", "target"}


def fixture_roots(workspace_root: Path) -> list[Path]:
    """Find outermost crate directories named fixtures, without following links."""
    crate_root = workspace_root / "crates"
    roots: list[Path] = []
    for current, directories, _ in os.walk(crate_root, followlinks=False):
        current_path = Path(current)
        directories[:] = sorted(
            directory
            for directory in directories
            if directory not in IGNORED_WORKSPACE_DIRS
            and not (current_path / directory).is_symlink()
        )
        if current_path.name == "fixtures":
            roots.append(current_path)
            directories[:] = []
    return roots


def fixture_hashes(workspace_root: Path) -> tuple[dict[str, str], list[str]]:
    """Return hashes for all regular files below fixture roots and scan errors."""
    hashes: dict[str, str] = {}
    errors: list[str] = []
    roots = fixture_roots(workspace_root)
    for root in roots:
        for current, directories, filenames in os.walk(root, followlinks=False):
            current_path = Path(current)
            linked_directories = sorted(
                directory
                for directory in directories
                if (current_path / directory).is_symlink()
            )
            for directory in linked_directories:
                path = current_path / directory
                errors.append(
                    f"fixture directory symlink is not supported: "
                    f"{path.relative_to(workspace_root).as_posix()}"
                )
            directories[:] = sorted(
                directory for directory in directories if directory not in linked_directories
            )
            for filename in sorted(filenames):
                path = current_path / filename
                relative = path.relative_to(workspace_root).as_posix()
                if path.is_symlink():
                    errors.append(f"fixture file symlink is not supported: {relative}")
                    continue
                if not path.is_file():
                    continue
                digest = hashlib.sha256(path.read_bytes()).hexdigest()
                hashes[relative] = digest
    return hashes, errors


def render_manifest(hashes: Mapping[str, str]) -> str:
    lines = [MANIFEST_HEADER]
    for path in sorted(hashes):
        lines.append(f"{hashes[path]}  {path}\n")
    return "".join(lines)


def validate_manifest(actual: Mapping[str, str], manifest_text: str) -> list[str]:
    expected: dict[str, str] = {}
    manifest_lines: dict[str, int] = {}
    errors: list[str] = []
    manifest_paths: list[str] = []

    for line_number, line in enumerate(manifest_text.splitlines(), start=1):
        if not line or line.startswith("#"):
            continue
        digest, separator, path_text = line.partition("  ")
        if not separator or not HASH_PATTERN.fullmatch(digest) or not path_text:
            errors.append(f"manifest line {line_number} must be '<sha256>  <path>'")
            continue
        path = PurePosixPath(path_text)
        if (
            path.is_absolute()
            or ".." in path.parts
            or path.parts[:1] != ("crates",)
            or "fixtures" not in path.parts
            or "\\" in path_text
        ):
            errors.append(f"manifest line {line_number} is not a crate fixture path: {path_text}")
            continue
        if path_text in expected:
            errors.append(f"manifest has duplicate fixture path: {path_text}")
            continue
        expected[path_text] = digest
        manifest_lines[path_text] = line_number
        manifest_paths.append(path_text)

    if manifest_paths != sorted(manifest_paths):
        errors.append("manifest fixture paths must be sorted")

    # Entries that have a pinned line point at that line in the manifest. An
    # unpinned checkout file has no manifest line, so it points at its own first line.
    for path in sorted(actual.keys() - expected.keys()):
        errors.append(f"{path}:1: fixture is missing from manifest: {path}")
    for path in sorted(expected.keys() - actual.keys()):
        errors.append(
            f"{MANIFEST_LABEL}:{manifest_lines[path]}: "
            f"manifest fixture is missing from checkout: {path}"
        )
    for path in sorted(actual.keys() & expected.keys()):
        if actual[path] != expected[path]:
            errors.append(
                f"{MANIFEST_LABEL}:{manifest_lines[path]}: fixture content hash changed: {path} "
                f"(manifest {expected[path]}, checkout {actual[path]})"
            )
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group()
    action.add_argument(
        "--check", action="store_true", help="compare the checkout with the pinned manifest"
    )
    action.add_argument("--update", action="store_true", help="rewrite the pinned manifest")
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="suppress success output; drift and scan errors are still reported",
    )
    args = parser.parse_args()

    hashes, scan_errors = fixture_hashes(WORKSPACE_ROOT)
    if scan_errors:
        print("fixture manifest scan failed:", file=sys.stderr)
        for error in scan_errors:
            print(f"  {error}", file=sys.stderr)
        return 1

    if args.update:
        MANIFEST_PATH.write_text(render_manifest(hashes), encoding="utf-8", newline="\n")
        if not args.quiet:
            print(f"updated {MANIFEST_PATH.relative_to(WORKSPACE_ROOT)}: {len(hashes)} files")
        return 0

    if not MANIFEST_PATH.is_file():
        print(f"fixture manifest does not exist: {MANIFEST_PATH}", file=sys.stderr)
        return 1
    errors = validate_manifest(hashes, MANIFEST_PATH.read_text(encoding="utf-8"))
    if errors:
        print("fixture manifest drift detected:", file=sys.stderr)
        for error in errors:
            print(f"  {error}", file=sys.stderr)
        print(f"fixture manifest drift total: {len(errors)}", file=sys.stderr)
        return 1

    if not args.quiet:
        print(
            f"fixture manifest matches {len(hashes)} files across "
            f"{len(fixture_roots(WORKSPACE_ROOT))} trees"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
