[package]
name = "orna-standard"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
orna-artifact = { path = "../orna-artifact" }
orna-core = { path = "../orna-core" }
orna-semantic-v1 = { path = "../orna-semantic-v1" }

[dev-dependencies]
orna-syntax-v1 = { path = "../orna-syntax-v1" }
